name: Ci

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
        - main
  workflow_dispatch:

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Display hello world
        run: npm install
      - name: run the build
        run: npm run build
      - name: run tests
        run: npm run test
