name: Ci

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
        - main
  workflow_dispatch:

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install npm
        run: npm install
      - name: run the build
        run: npm run build
      - name: run tests
        run: npm run test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
